# Generated by Django 5.0.6 on 2024-06-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_carrito_carritoproducto_producto_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='id_cliente',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
