# Generated by Django 5.0.6 on 2024-06-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_carrito_id_cliente_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoproducto',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
