# Generated by Django 5.0.6 on 2024-06-29 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_carritoproducto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoproducto',
            name='precio',
        ),
    ]
