# Generated by Django 5.0.6 on 2024-06-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_carro_remove_carritoproducto_carrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='imagen',
            field=models.ImageField(default='productos/default.png', upload_to='productos/'),
        ),
    ]
