# Generated by Django 5.0.6 on 2024-06-30 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_carro_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='imagen',
        ),
    ]
